\input texinfo

@setfilename gnus-coding-ja
@settitle Gnus Coding Style and Maintainance Guide
@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex pg cp

@dircategory Emacs
@direntry
* Gnus Coding-ja: (gnus-coding-ja).  Gnus Coding Style and Maintainance Guide
@end direntry

@copying
Copyright (c) 2004, 2005  Free Software Foundation, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU
Manual'', and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License'' in the Emacs manual.

この文書を、フリーソフトウェア財団発行の GNU フリー文書利用許諾契約書
第 1.2 版またはそれ以降の版が定める条件の下で複製、配布、あるいは変更す
ることを許可します。変更不可部分は指定しません。「A GNU Manual」は表表紙
テキスト、以下の (a) は裏表紙テキストです。この利用許諾契約書の複写は
「Emacs manual」の「GNU フリー文書利用許諾契約書」という章に含まれていま
す。

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

(a) FSF の裏表紙テキスト:「あなたにはこの GNU Manual を GNU ソフトウェア
のように複製したり変更する自由があります。複製はフリーソフトウェア財団に
よって出版されました。(フリーソフトウェア財団は) GNU の開発のために必要
な資金を集めています。」

This document is part of a collection distributed under the GNU Free
Documentation License.  If you want to distribute this document
separately from the collection, you can do so by adding a copy of the
license to the document, as described in section 6 of the license.

この文書は「GNU フリー文書利用許諾契約書」に基づいて配布された収集著作物
の一部です。もしあなたがこの文書を収集著作物から分離して配布したいときは、
契約書の第 6 項に記述されているように、文書に契約書の複写を付加すること
によって、行なうことができます。
@end quotation
@end copying

@titlepage
@title Gnus Coding Style and Maintainance Guide

@author by Reiner Steib  <Reiner.Steib@@gmx.de>

@insertcopying
@end titlepage

@c 明らかにこれは未成熟な草稿に過ぎません。とにかく、それを見とがめた誰
@c かが直してくれることを期待して、私たちはこれを CVS に置きました。;-)
@c 一部を直してくれるだけでもありがたいです。

@node Top
@top Gnus Coding Style and Maintainance Guide

このマニュアルは @dots{} を説明します。

@menu
* Gnus Coding Style:: Gnus でコードを書くときの流儀
* Gnus Maintainance Guide:: Gnus の維持管理に関する手引
@end menu

@node Gnus Coding Style
@section Gnus でコードを書くときの流儀
@subsection 依存関係

Gnus の配布は、Gnus のために書かれ Gnus のために集中的に使われるたくさん
のライブラリーを含んでいます。しかし、それらのライブラリーの多くはそれら
単独でも有用です。例えば他の Emacs Lisp パッケージが、@acronym{MIME} ラ
イブラリーを使うかもしれません。@xref{Top, ,Top, emacs-mime-ja, The
Emacs MIME Manual}.

@subsection 汎用ライブラリー

@table @file
@item netrc.el
@file{.netrc} を解析する機能を提供します。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item format-spec.el
任意のフォーマット文字列をフォーマットする関数群を提供します。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。
@end table

@subsection 暗号化とセキュリティー

@table @file
@item encrypt.el
ファイルを暗号化するルーチン群を提供します。
@c As of 2005-10-25...
このファイルは Gnus に依存しません。

@item password.el
利用者のパスワードを読み取り、パスワードキャッシュを使うこともあります。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item tls.el
GnuTLS で囲むラッパーを介して TLS/SSL をサポートします。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item pgg*.el
さまざまな PGP の実装のためのインターフェースを提供します。
@c As of 2005-10-21...
これらのファイルは Gnus に依存しません。
@end table

@subsection ネットワーキング

@table @file
@item dig.el
ドメイン名システム dig へのインターフェースです。
@c As of 2005-10-21...
このファイルに Gnus への重大な依存はありません。
@code{gnus-run-mode-hooks} (ラッパー関数) を使います。

@item dns*.el
ドメイン名サービスで調べます。
@c As of 2005-10-21...
これらのファイルは Gnus に依存しません。
@end table

@subsection RFC に関係するメールとニュースのライブラリー

@table @file
@item pop3.el
ポストオフィスプロトコル (RFC1460) へのインターフェースです。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item imap.el
@acronym{IMAP} ライブラリーです。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item ietf-drums.el
RFC822bis ヘッダーを解析する関数群を提供します。
@c As of 2005-10-21...
このファイルは Gnus に依存しません。

@item rfc1843.el
HZ (RFC1843) デコードを行ないます。HZ は中国語と @acronym{ASCII} 文字を
任意に混ぜ合わせた文章の、ファイル交換のためのデータです。
@c As of 2005-10-21...
@code{rfc1843-gnus-setup} は Gnus でだけ役に立つでしょう。Gnus への依存
を無くすために、この関数は別の場所に移設すべきかもしれません。これ以外に、
重大ではないけれども Gnus に依存している関
数 @code{rfc1843-decode-article-body} については、引数をオプションにする
ことによって、@code{gnus-newsgroup-name} を除外することができるでしょう。

@item rfc2045.el
RFC2045 ヘッダーをデコードする関数群を提供します。

@item rfc2047.el
RFC2047 メッセージをエンコードおよびデコードする関数群を提供します。

@item rfc2104.el
RFC2104 に基づくメッセージのハッシュによる認証のためのコードを提供します。

@item rfc2231.el
RFC2231 ヘッダーをデコードする関数群を提供します。

@item flow-fill.el
RFC2646 の "flowed" テキストを処理します。
@c As of 2005-10-27...
このファイルは Gnus に依存しません。
@end table

@subsection message

Gnus ではすべてのメッセージ (メールとニュースの両方) の作成を Message モー
ドのバッファーで行ないます。Message モードは Emacs のメールモードの置き
換えになることが意図されています。@file{message.el} は Gnus に依存しない
ようにすべきです。

@subsection Gnus バックエンド

@file{nn*.el} のファイル群は NNTP (@file{nntp.el}), IMAP
(@file{nnimap.el}) および複数の他のメールバックエンドの機能を提供しま
す (おそらく @file{nnml.el}, @file{nnfolder.el} およ
び @file{nnmaildir.el} が、もっとも広く使われているメールバックエンドで
す)。

@c message / gnus
@c
@c nn*
@c
@c mm*
@c
@c rfc*
@c
@c pgg*
@c tla netrc pop3 dig dns ...
@c format-spec.el

@section 互換性

@c v5-10 枝と幹における、XEmacs と古いバージョンの Emacs との互換性。

@c @table
@c x
@c @end table

@node Gnus Maintainance Guide
@chapter Gnus の維持管理に関する手引

@section 安定版と開発版

CVS の幹はかなり活発に開発されています。

@c 通常 Gnus は幹で開発されています。

@c 例外: 5.10.1 がリリースされた後の数ヶ月間、新機能の追加が凍結されまし
@c た。

@section 同期

@c 随所に関連する Message-ID があります。Gmane でそれらのスレッドを参照
@c するには http://thread.gmane.org/Message-ID を使って下さい (そして表
@c 題をクリックして下さい)。

@c Miles Bader さんのいくつかの記事から引用します...

@c <v9eklyke6b.fsf@marauder.physik.uni-ulm.de>
@c <buovfd71nkk.fsf@mctpc71.ucom.lsi.nec.co.jp>

Emacs で行なわれた変更を Gnus に取り込むことを、私は頻繁には行ないませ
ん。Gnus で行なわれた変更を Emacs に持ち上げるよりも多くの手作業を必要と
する傾向があるからです。

私はディフォルトで週一回の同期を行なっています。さらに私は Gnus メーリン
グリストのあらゆるスレッドを追いかけて、話し合われているどんな変更でも、
それがより最新になるようにしています (そのため、話題になっている変更への
追従は 1〜2日遅れます)。

@c <buovfd71nkk.fsf@mctpc71.ucom.lsi.nec.co.jp>

ついでに、同期に関するより詳しい説明を付記しておきましょう:

基本的に私が理解しているのは、Emacs と Gnus v5-10 におけるすべての共通な
ファイルを Emacs-Gnus ゲートウェイが同じにしてくれることです。ただし非常
に正当な理由がある (例えば Emacs では Gnus の版を表す文字列
が @samp{5.11} ですが v5-10 枝では @samp{5.10.何がし} のままになってい
る) 場合を除きます。さらに Emacs か v5-10 枝のどちらかで、それらのファイ
ルに対して行なわれたすべての変更は、Gnus の CVS の幹にも反映されます。た
だし、こちらも正当な理由がある場合を除きます (これまでの典型的な例外とし
て、効果は同じだけれども違うやり方で行なわれた変更がすでに幹に存在してい
たことがありました)。これによって、次に Emacs の Gnus を更新するときになっ
たら、それは非常に楽なはずです---Emacs だけで変更されたことが失われてし
まうことを心配せずに、Gnus の幹をそれらのファイルにどさっと置くだけで良
いのです。

この結果、ハッカーであるあなたは、通常は一つの場所で変更を行なうだけで済
むことになります:

@enumerate
@item
Gnus の外にあると見なされるファイル (例えば新しい @file{encrypt.el}) の
場合、おそらく Emacs で変更を行なうべきです。それは二〜三日後に Gnus に
現われるでしょう。

Emacs の CVS への書き込みが許されていない (またはそれが不便) ならば、
v5-10 枝で変更を行なえば良いでしょう。それは Emacs の CVS に伝搬されるは
ずです---しかし、それが論争の的になる可能性があって、メーリングリストで
議論することが必要かどうかを判断するために、追加の調査が (私によって) 行
なわれるでしょう。[しかし多くの変更は明らかなバグの修正なので、たいてい
の場合は問題ありません。]

@item
Gnus のファイルへの変更で、それが十分に重要な Emacs と v5-10 枝の部分で
あるのならば、変更は v5-10 枝で行なえば良いでしょう。そしてそれ
は Emacs の CVS と Gnus の CVS の幹に反映されるでしょう (二〜三日後に)。

(おそらく、対象になるソースコードが v5-10 枝と Gnus の CVS の幹で異なる
ために) 衝突を生じることがわかっている場合は、あなたの変更を両方の場所に
インストールして下さい。そして、私がそれらを同期させようとすると衝突する
でしょう---そういうほとんどの場合に _とにかく_ 衝突します。でも、私が二
つの「同一の」変更を調べる場合に、それを解決してかつ実際にコードを修正し
なければならないことに比べれば、適切なものを選ぶだけで済む方が、多くの場
合、私にはより簡単です。

@item
Gnus の開発における雑多な変更については、単に Gnus の CVS の幹を変更すれ
ば、それは Emacs に反映されるでしょう。二〜三年後に@dots{} :-)
@end enumerate

もちろんどんな場合でも、私が同期させる作業を待てないのであれば、あなたの
変更を二つ以上の場所にチェックインすることはできるし、恐らく問題にならな
いでしょう。通常、変更は文字どおりにとにかく同一ですから、容易に自動的に
解決することができます (ときどき私はそのように重複して行なわれるチェック
インの中でお間抜けなもの、例えば空白文字の違いに気づいて、それらを統一し
ますけれどね ;-)。

@section いろんなこと

@heading @file{GNUS-NEWS}

@file{texi/gnus-news.texi} を元に @file{GNUS-NEWS} を生成させるのは、No
Gnus から始まりました。@file{GNUS-NEWS} は編集しないで下さい。
@file{texi/gnus-news.texi} を編集し、@file{texi} ディレクトリー
で @command{make GNUS-NEWS} をタイプしてから、
@file{GNUS-NEWS} と @file{texi/gnus-news.texi} をチェックインして下さい。

@c Local Variables:
@c coding: iso-2022-7bit
@c fill-column: 72
@c mode: texinfo
@c use-kuten-for-period: t
@c use-touten-for-comma: t
@c End:
