\input texinfo                  @c -*-texinfo-*-

@setfilename sieve-ja
@settitle Emacs Sieve Manual
@synindex fn cp
@synindex vr cp
@synindex pg cp
@iftex
@firstparagraphindent insert
@end iftex

@copying
This file documents the Emacs Sieve package.

Copyright @copyright{} 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008
Free Software Foundation, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual'',
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled ``GNU Free Documentation License''.

この文書を、フリーソフトウェア財団発行の GNU フリー文書利用許諾契約書
第 1.2 版またはそれ以降の版が定める条件の下で複製、配布、あるいは変更す
ることを許可します。変更不可部分は指定しません。“A GNU Manual”は表表紙
テキスト、以下の (a) は裏表紙テキストです。この利用許諾契約書の複写は
「GNU フリー文書利用許諾契約書」という章に含まれています。

(a) The FSF's Back-Cover Text is: ``You have the freedom to copy and
modify this GNU manual.  Buying copies from the FSF supports it in
developing GNU and promoting software freedom.''

(a) FSF の裏表紙テキスト:「あなたにはこの GNU Manual を複製したり変更す
る自由があります。FSF からの複写の購入は GNU の開発とソフトウェアの自由
の促進を支援します。」
@end quotation
@end copying

@dircategory Emacs
@direntry
* Sieve-ja: (sieve-ja).         Managing Sieve scripts in Emacs (Japanese).
@end direntry
@iftex
@finalout
@end iftex
@setchapternewpage odd

@titlepage
@title Emacs Sieve Manual

@author by Simon Josefsson
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@node Top
@top Sieve Support for Emacs

このマニュアルは Emacs Sieve パッケージの説明書です。

これは Sieve モードと「Sieve-管理」(Manage Sieve) のためのユーザーズマニュ
アルとして、および @samp{sieve-manage} プロトコルを扱う Emacs Lisp
API のためのリファレンスマニュアルとして活用されることを意図しています。

Sieve はサーバー側でメールを濾過するための言語です。その言語は RFC
3028 に文書化されています。このマニュアルの目的は言語を説明することでは
ないので、RFC 3028 は手元に置いておいてください。

まともな Sieve の資料は @uref{http://www.cyrusoft.com/sieve/} にあります。

訳注: Sieve == 篩 (ふるい)

@menu
* Installation::          このパッケージを使うための準備
* Sieve Mode::            Sieve スクリプトの編集
* Managing Sieve::        遠隔サーバー上の Sieve スクリプトを管理する
* Examples ::             Sieve コードの片鱗
* Manage Sieve API ::     「Sieve-管理」プロトコル API のインターフェース
* Standards::             使われている RFC と作業文書の概略
* GNU Free Documentation License:: この文書の利用許諾契約書
* Index::                 関数および変数の索引
@end menu

@node Installation
@chapter インストール
@cindex Install
@cindex Setup

Sieve パッケージはあなたの Emacs の版に付属していて、すぐに使えるように
なっているはずです。

そうなっていないのであれば、このパッケージを手作業で設定するために、以下
のコマンドを @code{~/.emacs} ファイルに書き込んでください:

@lisp
(autoload 'sieve-mode "sieve-mode")
@end lisp
@lisp
(setq auto-mode-alist (cons '("\\.s\\(v\\|iv\\|ieve\\)\\'" . sieve-mode)
                            auto-mode-alist))
@end lisp

@node Sieve Mode
@chapter Sieve モード

Sieve モードは、構文に基づいたインデント、font-lock のサポート、およ
び Sieve スクリプトを楽に編集できるようにするためのその他の便利な機能を
提供します。

このメジャーモードに切り替えるには @samp{M-x sieve-mode} を使ってくださ
い。このコマンドは @code{sieve-mode-hook} で与えられたフックを実行します。

@vindex sieve-mode-map
@vindex sieve-mode-syntax-table
Sieve モードは @code{c-mode} から派生していて、コメントの構文以外はとて
も似ています。インデントをカスタマイズする変数があるのと同様に、キーマッ
プ (@code{sieve-mode-map}) は @code{c-mode} のものを受け継ぎます。
Sieve モードは専用の略語表 (@code{sieve-mode-abbrev-table}) と構文テーブ
ル (@code{sieve-mode-syntax-table}) を持っています。

編集に役立つ関数に加えて、Sieve モードには Sieve スクリプトを遠隔管理す
るためのキー設定もあります。@xref{Managing Sieve}.

@table @kbd
@item C-c RET
@kindex C-c RET
@findex sieve-manage
@cindex manage remote sieve script
「Sieve-管理」プロトコル (Managesieve protocol) を使って、遠隔サーバーに
接続します。

@item C-c C-l
@kindex C-c C-l
@findex sieve-upload
@cindex upload sieve script
現在接続しているサーバーに Sieve スクリプトをアップロードします。
@end table

@node Managing Sieve
@chapter Sieve の管理

「Sieve-管理」は、遠隔サーバーにある Sieve スクリプトを表示するために使
われる特別なモードです。それは @kbd{M-x sieve-manage RET} で起動し、その
サーバーにおけるユーザー名と、必要な場合には資格証明書 (credentials) の
入力を求めます。

サーバーとの接続に成功すると、「Sieve-管理」バッファーには以下のようなも
のが表示されます:

@example
Server  : mailserver:2000

2 scripts on server, press RET on a script name edits it, or
press RET on <new script> to create a new script.
        <new script>
 ACTIVE .sieve
        template.siv
@end example

スクリプトの一つが強調表示され、標準のポイント移動コマンド (@kbd{<up>},
@kbd{<down>} など) でリスト内を移動することができます。

以下のコマンドが「Sieve-管理」バッファーで利用可能です:

@table @kbd
@item m
@kindex m
@findex sieve-activate
現在の強調表示されたスクリプトを活性化します。

@item u
@kindex u
@findex sieve-deactivate
現在の強調表示されたスクリプトを不活性化します。

@item C-M-?
@kindex C-M-?
@findex sieve-deactivate-all
すべてのスクリプトを不活性化します。

@item r
@kindex r
@findex sieve-remove
現在の強調表示されたスクリプトを取り除きます。

@item RET
@item mouse-2
@item f
@kindex RET
@kindex mouse-2
@kindex f
@findex sieve-edit-script
サーバーバッファーを隠して、現在の強調表示されたスクリプトを Sieve モー
ド (@pxref{Sieve Mode}) で編集するための新しいバッファーにダウンロードし
ます。

@item o
@kindex o
@findex sieve-edit-script-other-window
Sieve モード (@pxref{Sieve Mode}) で編集するために、現在の強調表示された
スクリプトを含んでいる新しいバッファーを、別ウィンドウで作成します。

@item q
@kindex q
@findex sieve-bury-buffer
接続を切らずに「Sieve-管理」バッファーを隠します。

@item ?
@item h
@kindex ?
@kindex h
@findex sieve-help
ミニバッファーにヘルプを表示します。
@end table

@node Examples
@chapter 例

Sieve を熟知していないなら、この章にほんの少しだけあるコードの断片を利用
すれば良いでしょう。Sieve 言語でゼロから規則を書くことがもっと快適に感じ
られるようになるまでは、それらをカット＆ペーストして好きなように変更して
ください。

以下の完全な Sieve スクリプトは、合致する @samp{Sender:} ヘッダーを持つ
すべてのメッセージを、指定されたメールボックスに格納します。多くのメーリ
ングリストがこの形式を使っています。最初の行は Sieve サーバーが確実
に @code{fileinto} コマンドを理解できるようにするためのものです。

@example
require "fileinto";

if address "sender" "owner-w3-beta@@xemacs.org" @{
	fileinto "INBOX.w3-beta";
@}
@end example

少数のメーリングリストは @samp{Sender:} ヘッダーを使いませんが、ある別の
ヘッダーに独特の識別子があります。以下のスクリプトは完全ではなく、すで
に @code{fileinto} が読み込まれていることを仮定しています。

@example
if header :contains "Delivered-To" "auc-tex@@sunsite.dk" @{
	fileinto "INBOX.auc-tex";
@}
@end example

最後は、どんな独特の識別子も持っていない絶望的なメーリングリストのために、
@samp{To:} と @samp{Cc} ヘッダーにおける合致を強いられる例です。前のもの
と同様に、この断片は @code{fileinto} が読み込まれていることを仮定してい
ます。

@example
if address ["to", "cc"] "kerberos@@mit.edu" @{
	fileinto "INBOX.kerberos";
@}
@end example

@node Manage Sieve API
@chapter 「Sieve-管理」の API

@file{sieve-manage.el} ライブラリーには @sc{managesieve} プロトコルでサー
バーと話すための、低階層の関数群があります。

いくつかの、ユーザーが見ることができる変数があり、それらすべて
は @code{sieve} グループでカスタマイズすることができます (@kbd{M-x
customize-group RET sieve RET}):

@table @code
@item sieve-manage-default-user
@vindex sieve-manage-default-user
ディフォルトのユーザー名を設定します。

@item sieve-manage-default-port
@vindex sieve-manage-default-port
仕様するディフォルトのポートを設定します。提案されているポート番号
は @code{2000} です。

@item sieve-manage-log
@vindex sieve-manage-log
非-@code{nil} だったら、やり取りしたプロトコルの結果が記録されるバッファー
名の文字列でなければなりません (デバッグするときに使います)。
@end table

API の関数には以下のものがあります:

@table @code
@item sieve-manage-open
@findex sieve-manage-open
「Sieve-管理」サーバーに接続し、他のすべての API で使うバッファーを返し
ます。

@item sieve-manage-opened
@findex sieve-manage-opened
サーバーと接続しているか否かを検査します。

@item sieve-manage-close
@findex sieve-manage-close
サーバーとの接続を閉じます。

@item sieve-manage-authenticate
@findex sieve-manage-authenticate
サーバーを認証します。

@item sieve-manage-capability
@findex sieve-manage-capability
サーバーがサポートしている機能のリストを返します。

@item sieve-manage-listscripts
@findex sieve-manage-listscripts
サーバーにあるスクリプトを列挙します。

@item sieve-manage-havespace
@findex sieve-manage-havespace
与えられたサイズのスクリプトのための空きがあれば、非-@code{nil} を返しま
す。

@item sieve-manage-getscript
@findex sieve-manage-getscript
サーバーからスクリプトをダウンロードします。

@item sieve-manage-putscript
@findex sieve-manage-putscript
サーバーにスクリプトをアップロードします。

@item sieve-manage-setactive
@findex sieve-manage-setactive
サーバーにあるどのスクリプトが活きているはずであるかを示します。
@end table

@node Standards
@chapter 標準

Emacs Sieve パッケージは、少ないけれども増大することが望まれる RFC 群お
よび草稿文書の、すべてまたは一部分を実装します。この章では関連するものを
列挙します。それらはすべて @uref{http://quimby.gnus.org/notes/} から入手
することができます。

@table @dfn
@item RFC3028
Sieve: メール濾過言語

@item draft-martin-managesieve-03
Sieve スクリプトを遠隔管理するためのプロトコル
@end table

@node GNU Free Documentation License
@chapter GNU フリー文書利用許諾契約書

訳注: @uref{http://www.opensource.jp/fdl/fdl.ja.html.euc-jp,
非公式な日本語訳} があります。

@include doclicense.texi

@node Index
@unnumbered Index
@printindex cp

@summarycontents
@contents
@bye

@c Local Variables:
@c coding: iso-2022-7bit
@c fill-column: 72
@c mode: texinfo
@c use-kuten-for-period: t
@c use-touten-for-comma: t
@c End:
